export const informationMenu = [
    { to: "/admin/admin", label: "Admin Account", key: "admin", roles: ["Admin"] },
    { to: "/admin/advertisement", label: "Advertisement", key: "advertisement", roles: ["Admin", "Seller"] },
    { to: "/admin/brand", label: "Brand", key: "brand", roles: ["Admin", "Seller"] },
    { to: "/admin/category", label: "Category", key: "category", roles: ["Admin", "Seller"] },
    { to: "/admin/coupon", label: "Coupon", key: "coupon", roles: ["Admin", "Seller"] },
    { to: "/admin/customer", label: "Customer", key: "customer", roles: ["Admin", "Seller"] },
    { to: "/admin/feedback", label: "Feedback", key: "feedback", roles: ["Admin", "Seller"] },
    { to: "/admin/order", label: "Order", key: "order", roles: ["Admin", "Seller"] },
    { to: "/admin/payment", label: "Payment", key: "payment", roles: ["Admin", "Seller"] },
    { to: "/admin/payment-method", label: "Payment Method", key: "paymentmethod", roles: ["Admin", "Seller"] },
    { to: "/admin/post", label: "Post", key: "post", roles: ["Admin", "Seller"] },
    { to: "/admin/post-category", label: "Post Category", key: "postcategory", roles: ["Admin", "Seller"] },
    { to: "/admin/product", label: "Product", key: "product", roles: ["Admin", "Seller"] },
];